apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  name: jenkins
spec:
  replicas: 1
  selector:
    name: jenkins
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: jenkins
    spec:
      containers:
      - image: jenkins:latest
        imagePullPolicy: Always
        name: jenkins
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      serviceAccount: jenkins
  triggers:
  - type: ConfigChange
  - type: ImageChange
    imageChangeParams:
      automatic: true
      containerNames:
      - jenkins
      from:
        kind: ImageStreamTag
        name: jenkins:latest

status: {}
